### ISSUE TITLE
'EulerDiscreteScheduler' object has no attribute 'get_velocity'

### ISSUE THREAD

**Issue by LiuShiyu95** [pixeli99/SVD_Xtend#1]
Thank you very much for your work. I did not find any implementation of get in EulerDiscreteSchedule in diffusers_ Velocity, may I ask if you have implemented one yourself?

**Comment by pixeli99** [comment]
It seems that currently we only need to copy the function from DDPM, but the current version of the code has issues. I will continue to fix it tomorrow to fully align it with the noise scheduler in the svd paper. Once everything is ready, I will update the readme to indicate that the code is usable.

**Comment by LiuShiyu95** [comment]
> It seems that currently we only need to copy the function from DDPM, but the current version of the code has issues. I will continue to fix it tomorrow to fully align it with the noise scheduler in the svd paper. Once everything is ready, I will update the readme to indicate that the code is usable.

I understand what you mean, thank you for your work and thank you for your reply!
