### ISSUE TITLE
Support more conditional inputs, such as layout

### ISSUE THREAD

**Issue by zhw-zhang** [pixeli99/SVD_Xtend#10]
Hello, I saw a "Support more conditional inputs, such as layout" in the to-do list. What does this mean. Is it that the first frame + the BB trajectory of the subsequent frames are given to guide video generation? When will it probably be online?

**Comment by pixeli99** [comment]
Yes, you are right, I plan to support this feature, to enable trajectory to video controlled generation, just like what layout2image does.
If everything goes smoothly, a usable model should be released before New Year's Day.

**Comment by zhw-zhang** [comment]
ok, looking forward to your work.

**Comment by zhw-zhang** [comment]
Hi, I haven't seen the update of this project. Have you encountered any problems? Maybe we can solve it together.
