### ISSUE TITLE
May I ask what pretrained_model_name_or_path is

### ISSUE THREAD

**Issue by aoyingying** [pixeli99/SVD_Xtend#13]
May I ask what pretrained_model_name_or_path is，thank you

**Comment by aoyingying** [comment]
I know the answer

**Comment by liiiiiiiiil** [comment]
> I know the answer
Can you share that？

**Comment by zhanghaobucunzai** [comment]
问下这个文件下载到了吗

**Comment by 1585511010** [comment]
> 我知道答案

请问一下这个是svd_xt_image_decoder.safetensors吗，为什么我加上路径之后报错我配置的参数是pretrained_model_name_or_path="/SVD_Xtend-main/svd_xt_image_decoder.safetensors"然后就报错
raise EnvironmentError(f"It looks like the config file at '{config_file}' is not a valid JSON file.")
OSError: It looks like the config file at '/SVD_Xtend-main/svd_xt_image_decoder.safetensors' is not a valid JSON file.
是不是我下载的这个不是预训练权重文件
