### ISSUE TITLE
Maybe there's a mistake with the value range when sending the image into the VAE.

### ISSUE THREAD

**Issue by bugWholesaler** [pixeli99/SVD_Xtend#16]
[here](https://github.com/pixeli99/SVD_Xtend/blob/main/train_svd.py#L1001) you send an image with values ranging from [0,1] into the VAE, but the VAE expects the input value range to be [-1, 1].

**Comment by sayakpaul** [comment]
Yes, that indeed seems to be the case.

**Comment by pixeli99** [comment]
Yes, I overlooked this aspect, the normalization for images in my dataloader is incorrect, I will fix this.

**Comment by pixeli99** [comment]
Fixed.
5d155c1326f1a5db45618054f222c867c59067ef

**Comment by tykim0507** [comment]
Can somebody explain why should the input range be [-1,1] for the vae? Is it because it was trained like that?
