### ISSUE TITLE
Questions about the predicted_noise of EDM framework.

### ISSUE THREAD

**Issue by Pandint** [pixeli99/SVD_Xtend#19]
Sorry to disturb you again.

I am trying to accelerate SVD with DDIM, but in the EDM training framework, I didn't find how to calculate the predicted_noise with sigmas and model_pred. Can you help me?

**Comment by Pandint** [comment]
I derivate from the EulerDiscreteScheduler and obtain the results as follows:
denoised_latents = model_pred * (-sigma / (sigma**2 + 1) ** 0.5) + (noisy_latents / (sigma**2 + 1))
predicted_noise = model_pred * (1 / (sigmas**2 + 1) ** 0.5) - (noisy_latents * sigmas/ (sigmas**2 + 1))

I think this might be right.

**Comment by pixeli99** [comment]
Hi, actually I don't quite understand your motivation. Are you looking to change the sampling method of SVD to DDIM?

**Comment by Pandint** [comment]
Yes. And DDIM needs to take pred_noise and model_pred as input.
