### ISSUE TITLE
Which BDD100K data is used for training?

### ISSUE THREAD

**Issue by canqin001** [pixeli99/SVD_Xtend#20]
Hi @pixeli99 , thank you for your amazing work! I just read your code and wondering which subset of bdd100 data (I have not found the "bdd100k/images/track/mini" in their official web) is used for your training?

**Comment by pixeli99** [comment]
I apologize for the confusion. The situation is such that "mini" simply refers to the 5 videos I personally selected from the bdd tracking dataset for overfitting experiments. Therefore, you can choose the training data to use on your own. Specifically, I selected them from http://dl.yf.io/bdd100k/mot20/.

**Comment by canqin001** [comment]
Thank you so much for your explanation! One more question: how to modify the  "def __getitem__(self, ):" to make it work?
