### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by AbrahamYabo** [pixeli99/SVD_Xtend#27]
How much GPU memory is used for resolution of 512*320 and batch size of 1?

**Comment by pixeli99** [comment]
This depends on which parameters you have activated for training, if you fully activate unet, it might require around 60GB of GPU memory, therefore if you're encountering out-of-memory issues, it is recommended to train only a small subset of parameters.

**Comment by AbrahamYabo** [comment]
Thank you for your reply.
