### ISSUE TITLE
Question about the forward pass 

### ISSUE THREAD

**Issue by KKN18** [pixeli99/SVD_Xtend#32]
Hi,

While exploring diffusion models, I noticed the standard forward pass often uses the formula 
$\alpha \cdot x + \sigma \cdot \epsilon$. 
However, in your video diffusion model code, I saw a different approach:
```
sigmas = rand_log_normal(shape=[bsz,], loc=0.7, scale=1.6).to(latents.device)
noisy_latents = latents + noise * sigmas
inp_noisy_latents = noisy_latents / ((sigmas**2 + 1) ** 0.5)
```
You're sampling noise levels from a log-normal distribution and I'm curious about the reasoning behind this choice. 
If there are any papers or references that guided this decision, could you share them?

Thanks for your insights!

**Comment by Semolce9** [comment]
I guess it's because the training framework of SVD is not ddpm-based. In ddpm the forward pass is as you mentioned. SVD adopt EDM framework (https://arxiv.org/pdf/2206.00364.pdf). It's forward process is different from ddpm's. But I'm also do not familiar woth EDM so it's just a simple guess.

**Comment by tarashakhurana** [comment]
Do you have any insight on why in this code, the MSE loss is computed with the target latents (so the UNet is learning to predict the denoised sample, `x_0`) but during inference, the Euler Discrete sampler expects the output of the diffusion model to be `v_prediction`, not `x_0` or `epsilon`?
