### ISSUE TITLE
training gpu cost

### ISSUE THREAD

**Issue by zhw-zhang** [pixeli99/SVD_Xtend#4]
Hi, thank you for your open-source code. How much GPU consumption is required during training? Is it necessary to add additional deepspeed or checkpoint to save training memory consumption?

**Comment by pixeli99** [comment]
This depends on your specific training setup, with my current configuration (512*320, 16 frames, with all parameters of unet trainable), it will use approximately 63GB of VRAM (I haven't enabled any optimizations, such as deepspeed and so on)

**Comment by zhw-zhang** [comment]
Thank you for your reply. So your batchsize is 1? At 512*320 resolution.

**Comment by pixeli99** [comment]
Yes, batchsize=1
