### ISSUE TITLE
Add a short inference script loading from checkpoint?

### ISSUE THREAD

**Issue by chitianhao** [pixeli99/SVD_Xtend#47]
Impressive work!

Can you also add a short inference script to load from the checkpoint and do inference on image?

**Comment by pixeli99** [comment]
Thank you very much for your suggestion, I will provide a script to do the inference!

**Comment by pixeli99** [comment]
Hello, I have added a sample inference code, hopefully it will be helpful~

**Comment by chitianhao** [comment]
Thanks so much!
