### ISSUE TITLE
pretrained_model_name_or_path报错

### ISSUE THREAD

**Issue by 1585511010** [pixeli99/SVD_Xtend#52]
请问一下这个是svd_xt_image_decoder.safetensors吗，为什么我加上路径之后报错我配置的参数是pretrained_model_name_or_path="/SVD_Xtend-main/svd_xt_image_decoder.safetensors"然后就报错
raise EnvironmentError(f"It looks like the config file at '{config_file}' is not a valid JSON file.")
OSError: It looks like the config file at '/SVD_Xtend-main/svd_xt_image_decoder.safetensors' is not a valid JSON file.
是不是我下载的这个不是预训练权重文件

**Comment by KhaledButainy** [comment]
Try adding the repo ID from HuggingFace

**Comment by pixeli99** [comment]
use this

"stabilityai/stable-video-diffusion-img2vid"
