### ISSUE TITLE
Provide requirements.txt by running `pip3 freeze > requirements.txt` from a working development environment

### ISSUE THREAD

**Issue by danielvegamyhre** [pixeli99/SVD_Xtend#59]
I've been debugging some errors which seem to be due to version compatibilities between dependencies. It would be helpful if you could run `pip3 freeze > requirements.txt` in a working environment and add the resulting `requirements.txt` file to the repo so others can install the same pinned versions of dependency packages.

**Comment by pixeli99** [comment]
Thank you for the reminder, it has been updated 😀
