### ISSUE TITLE
Hyperparameters configuration for training

### ISSUE THREAD

**Issue by MyNiuuu** [pixeli99/SVD_Xtend#6]
Hi! Thank you so much for this helpful implementation! 

I am interested in the configuration of the hyperparameters you use to finetune the SVD. Do you just use the default value written in the `parse_args()`( e.g., lr=1e-4, conditioning_dropout_prob=0.1, etc.)? I would be deeply appreciated if a training script could be provided.

**Comment by BlakeOne** [comment]
I've been super curious too about what command-line arguments you're using - it would be a good addition to the readme IMO.

**Comment by pixeli99** [comment]
Alright, I will update the readme, so that everyone can use it for reference.
