### ISSUE TITLE
Text Embedding Support

### ISSUE THREAD

**Issue by junwei0001** [pixeli99/SVD_Xtend#68]
Hello,

Thanks for open sourcing your work on fine tuning SVD. Could you please provide us with some guidelines on how to include any text embeddings during fine tuning and inference? Any insights or suggestions would be greatly appreciated.

Thank you!

**Comment by pixeli99** [comment]
hi, @junwei0001 

Thanks for your question.

If you want to introduce text conditions, I think you can refer to https://github.com/pixeli99/SVD_Xtend/pull/14.
In summary, you only need to feed the text embedding into the model in a cross-attention moudle.

However, I tend to think that doing this requires medium-scale training to be feasible. At least, my previous attempts with small-scale data have not succeeded in implementing text2video. I hope this is helpful to you.
